apiVersion: v1
kind: Service
metadata:
  name: view-service
spec:
  selector:
    app: view-service
  type: NodePort
  ports:
    - name: http
      port: 9090
      targetPort: 9090
      protocol: TCP